### ISSUE TITLE
Stones converter

### ISSUE THREAD

**Issue by joshuagrier** [joshuagrier/oxrse_unit_conv#1]
### Name (Abbreviation) of the unit you want to create?

Stones

### What is its base SI unit?

kilograms

### Would you like to provide more information about your unit?

Please add the capability to convert this unit to our code, and I will accept it if I deem it good enough

### Contributor Guide

- [X] I will comply with the [Contributor Guide](../../CONTRIBUTING.md)

### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](../../CODE_OF_CONDUCT.md)

**Comment by joshuagrier** [comment]
First we need to establish a naming convention I suggest rolling_unit_name_version number for the name of the new feature branch

**Comment by secunderwood** [comment]
no why don't you do it I'm busy creating my own issues

**Comment by joshuagrier** [comment]
Because you've agreed to be my collaborator, but I can find other collaborators if you would rather not

**Comment by secunderwood** [comment]
ok valid give me 5

**Comment by secunderwood** [comment]
so will my branch be called rolling_stone_sarah_1

**Comment by joshuagrier** [comment]
That's exactly what I meant, perfect

**Comment by secunderwood** [comment]
great news thanks josh
